name: testing
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  stan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install project dependencies
        working-directory: ./
        run: composer install

      - name: Running PHPStan
        run: composer run phpstan

      - name: Running tests
        run: composer run test
