name: testing
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  stan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'

      - name: Install dependencies
        working-directory: ./
        run: composer install

      - name: Run PHPStan
        run: php vendor/bin/phpstan analyse

      - name: Run tests
        run: php vendor/bin/phpunit tests/
