name: testing
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  stan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: php-actions/composer@v6
        with:
          php_version: 8.3
          memory_limit: -1
          php_extensions: intl zip gd

      - name: Install dependencies
        working-directory: ./
        run: composer install

      - name: Run PHPStan
        run: composer run phpstan

      - name: Run tests
        run: composer run test
